### ISSUE TITLE
AI should use same logic for building as the players.

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#135]
The AI uses its own building logic.

This makes it able to cheat, it doesnt listen to the build speeds as the `cItemBuilder`.  It also does not use upgrades.

There are a few steps to take:

- [x] use itemBuilder for units
- [x] use itemBuilder for structures
- [x] make AI use upgrades
   - [x] Constyard: 4SLAB
   - [x] Constyard: Rturret
   - [x] LightFctry: QUAD (if applicable)
   - [x] WOR: Troopers (if applicable)
   - [x] Barracks: Infantry (if applicable)
   - [x] HeavyFctry: MVC
   - [x] HeavyFctry: Launcher (if applicable, Ordos doesnt have this)
   - [x] HeavyFctry: Siege Tank
- [x] Starport? (delegated to #143)
- [x] Repair facility? (delegated to #144)
- [x] general improvements (refactor some code?, de-duplicate stuff, more logical AI stuff?)

- [x] prevent AI going out of power. Ie let it build Windtrap first when it figures it will have low power after building the desired structure. (delegate to #145 - this out of power behavior is not new)

- [x] debug key F2 (win / destroy all from AI) makes game crash? (something with destruction of ItemBuilder perhaps?)

**Comment by stefanhendriks** [comment]
This is worked on in branch `feature/improve-ai`
