### ISSUE TITLE
0.6 feedback

### ISSUE THREAD

**Issue by sardaukar** [stefanhendriks/Dune-II---The-Maker#287]
Congrats on releasing 0.6! Some points of feedback:

- [x] sandwords are almost impossible to kill, and always hungry. I must have lost 30 units to them in one mission. In the original game they were both easier to kill, and less hungry (#288, #289)
- [x] it is not possible to move units by clicking a location on the minimap #291 (moved to 0.7.0 list)
- [x] there should be a separate cursor state to place buildings. now, if I have a unit selected and I place a building, the unit will head to the building - the original game kept building placement and unit movement separate #290
- [x] units overlap on the field. If I have a unit going south and another going north, and they meet, the north one will turn left and the south one will turn right, which makes them overlap. maybe both turning the same direction would fix it (Stefan: rendering issue z-index related?) #100 ? (moved to 0.7.0 list)
- [x] turrets are way too fast to track and fire, and repair way too quickly (#86). they also shoot through buildings, ie without line of sight. it's impossible to take down a line of 5 turrets without a huge amount of units  #295 / @sardaukar lets discuss there
- [x] it's not (always?) possible to place 4-slabs partially. sometimes you want to place a 4-slab to cover a 2- or 3- slab place (because of sand) but the 4-slab disappears when placed #299
- [x] rocket launchers are way too accurate. In the original game, they'd hit 0% of shots at point blank, and would improve with distance, but don't think they were 100% accurate like now #300 (The accuracy is reduced the closer a Rocket Launcher gets to target. By default they are at 100% accurate due to the correct distance. Perhaps change that? Please discuss at ticket)
- [x] troopers' rocket launchers have an insane range. I think I saw some shooting like 6 squares in diagonal defending a base #294
- [x] sometimes enemy units at bases don't do anything, even as the base is being destroyed around them #293
- [x] attacking an enemy harvester does not make enemy units come to its rescue, leaving their base  #298
- [x] your own units are too eager to attack enemies now, and can see them a mile away - which is a problem because they keep attacking enemies farther and farther away from your base and reach the enemy base sometimes, which makes them get destroyed by turrets or bigger enemy forces #297
- [x] #296
- [x] carryalls do a lot of loops in small spaces
- [x] the attack cursor should make the target unit blink if you target an enemy unit, instead of always pointing at a point on the floor #292 (moved to 0.7.0 list)
- [x] it should be possible to shift-click or press A to attack a point on the floor, to destroy spice blooms for example (already possible)
- [x] would be cool to be able to save/load and set options, like the scroll speed and resolution #94 #50  (moved to 0.7.0 list)
- [x] also cool to have a scoring screen and high-score table :D (#102 ) (moved to 0.7.0 list)

Huge improvement over 0.5, looking forward to 0.7!

**Comment by stefanhendriks** [comment]
Awesome, thx for the feedback.

About:
```
it should be possible to shift-click or press A to attack a point on the floor, to destroy spice blooms for example
```

This is with CTRL-Click, (force attack). Other than that all good suggestions/feedback. Thanks!

**Comment by stefanhendriks** [comment]
@sardaukar about `it is not possible to move units by clicking a location on the minimap` -> I actually noticed it was less important due to zooming. But I will add it to the list of GH tickets :)

**Comment by stefanhendriks** [comment]
@sardaukar - with 0.7.0 released, I was wondering if you had a similar list about that. Although there are still some points in this ticket left to do...

**Comment by sardaukar** [comment]
Added new issue https://github.com/stefanhendriks/Dune-II---The-Maker/issues/544

**Comment by stefanhendriks** [comment]
haha you made it so big again ;-) but I like feedback. Makes the game even better. And you couldn't wait for the weekend. That's nice ;-)

**Comment by stefanhendriks** [comment]
Moved the few open points in this list to the 0.7.0 list (#544) so I can close this list.
