### ISSUE TITLE
Sandworms should be "killable"

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#289]
From #287 

```
sandworms are almost impossible to kill, and always hungry. I must have lost 30 units to them in one mission. In the original game they were both easier to kill, and less hungry
```

Sandworm should have less HP, and, after < 50% it should disappear. It should re-appear (respawn?) after a certain amount of time.

## TODO
- [x] Give sandworm less HP
- [x] When sandworm is below x% of HP, make it disappear (ie hibernate?)
- [x] Sandworm should re-appear (respawn/regenerate?) after some time (delegated to #341 )

Sandworms don't really get *killed* ie, they will remain.
