### ISSUE TITLE
Graphical Improvements - Structures

### ISSUE THREAD

**Issue by rozmy** [stefanhendriks/Dune-II---The-Maker#348]
The goal is to separate flags from structures to make individual animations for building, damage and idle states. So that we can have fluent animations, while retaining the Dune 2 feel.

Steps:
- Cleanup and idle animation.
- Change shadow layers if needed
- Apply new gfx in game (@stefanhendriks )

## TODO [@rozmy](https://github.com/rozmy)
- [x] Large flag animation without pole
- [x] Small flag
- [x] Crop flag
- [x] Slab variations
- [x] Baracks
- [x] Construction yard
- [x] Ix
- [x] Polish Ix
- [x] Light factory
- [x] Heavy factory
- [x] Fix Heavy shadow frames
- [x] Fix Heavy Factory shadows
- [x] Fix Dome animation frame
- [x] Radar
- [x] Radar shadow with shades
- [x] Silo
- [x] Windtrap
- [x] Wor
- [x] High tech 
- [x] Refinery
- [x] Fix refinery palette (8bit)
- [x] Add Refinery fade effect
- [x] Add Starport fade effect
- [x] Repair
- [x] Add extra keyframes to Repair
- [x] Palace
- [x] Starport
- [x] Add starport shadow

## TODO @stefanhendriks 
Would need to position the new flags (small or large). And use the gfx.

- [x] Baracks
- [x] Construction yard
- [x] Ix
- [x] Light factory
- [x] Heavy factory
- [x] Radar
- [x] Silo
- [x] Windtrap
- [x] Wor
- [x] High tech 
- [x] Refinery
- [x] Repair
- [x] Palace
- [x] Starport
- [x] Add Refinery fade effect
- [x] Add Starport fade effect
- [x] Slab variations

**Comment by stefanhendriks** [comment]
@rozmy I have processed most structures.

3 things left:
- refinery (new animation)
- slab variations (would be nice to have them as terrain , look at rock bmp for example)
- fix smoke (what needs fixing?)

After this we can close this ticket! 🎉

**Comment by stefanhendriks** [comment]
with the refinery animation in, we should consider the starport as well - for consistency :)
