### ISSUE TITLE
Redo mouse/keyboard logic

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#367]
(originally: Holding CTRL and pressing somewhere for rally-point simply no longer works.)

Changes for #290 broke setting rally-point behavior. While trying to fix that it became obvious that event-driven vs 'everything in one big mess' driven bite each other. In other words, it is best to redo this using the event-driven way.

## TODO
- [x] select structure
- [x] select structure while having a group of units selected
- [x] deselect structure (won't do)
- [x] select / deselect unit (single click)
- [x] select multiple units (box-selecting) from "normal" mouse state
- [x] select multiple units (box-selecting) from "units already selected" mouse state
- [x] repair state
   - [x] repair unit (press `R` to switch to that state, press `R` again, or right-mouse click to leave Repair state)
   - [x] repair structure 
- [x] add units to selection when holding `SHIFT` 
- [x] place structure (mouse state)
- [x] deploy super weapon (mouse state) (deferred to #399)
- [x] force attack (hold key: `CTRL`)
- [x] force move (?)
- [x] set rally-point (with right-mouse button instead of CTRL-click)
- [x] react to keypress (key observer, like mouse)?
   - [x] create groups (`CTRL-1/5`)
   - [x] add to group (hold `SHIFT`)
   - [x] select units by group nr
   - [x] (required: report all keys pressed, or held for event, so that we can know if CTRL-1 is pressed for instance))
