### ISSUE TITLE
Weaken dependency on Allegro so that we can upgrade to another library

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#57]
D2TM is tightly coupled with Allegro 4.2. Since that Allegro version is deprecated and upgrading to a newer Allegro version (5.x) is as painful as migrating to any other library, it becomes clear that the dependency on Allegro 4.x has to be weakened to make a migration possible and less painful.

Current known dependencies
- [ ] ALFONT (might be fine to leave this, and migrate this along with Allegro, this seems kind of trivial?)
- [x] ALMP3 (can be removed, feature is broken anyway) (#388)
- [x] FBLEND (equivalent Allegro 4.x functions exists) (#387)
- [ ] `.dat` files (ALDATA?) -> #385 

Once the above has been done we can start working on #386 

Also, once we can migrate to another library, it would become much easier to make D2TM cross-platform (#58 )

**Comment by stefanhendriks** [comment]
Another contender: https://www.raylib.com/ ?

**Comment by Mira-Chronos** [comment]
No longer needed since migration to SDL2
