### ISSUE TITLE
Scroll map with holding right mouse button

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#63]
New controls use that (ie in C&C Remastered). Hold mouse button, then move mouse (from the position the mouse was held) and use the difference to tell how to move the viewport.

## todo
- [x] Hold right mouse button, and move causes map to move to that direction.
- [x] the further away from the point you started dragging mouse, the faster the movement should be
- [x] should take zooming factor into account (#65)
- [x] should *not* deselect selected units
