### ISSUE TITLE
Ability to zoom in / out of map

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#65]
Like Dune The Golden Path does, or C&C Remastered. Using mouse wheel, scrolling causes map zooming.

With Allegro 4 it should be possible using stretched blitting.

Progress at 23-08-2020 -> https://forum.dune2k.com/topic/20495-d2tm-progress/?do=findComment&comment=400042

To get a feel what we're aiming at, see https://youtu.be/ORB9bmFvSEY?t=301 and https://youtu.be/8UxdPwxDTEQ?t=386

## TODO

- [x] units do not attack when ordering units to attack a zoomed in structure
- [x] When zoomed (in or out), ordering units to attack makes units freeze. (ie, they stop moving, even when half-way cell, and they don't do anything else. They won't attack, nor move). When resetting zoom (with z), then clicking on structure to attack works as expected. (related to above?)
- [x] crashing when zooming too far out
- [x] drawing of shroud broken
- [x] Windtrap drawing broken
- [x] Drawing of placing structure is not taking zoom factor into account
- [x] When zoomed out, the repair icons on structures are still 100% which looks weird (icons are bigger than structure)
- [x] Windtrap shadow offset is wrong when zooming.
- [x] Prebuild animation is still not zoomed
- [x] Particles (smoke, explosions, etc) that have been placed are not rendered at the correct place when zooming
- [x] minimap broken (rectangle no longer rendered, and clicking on it does not work as expected)
- [x] use own stretch blit that does a bit more safety checking?
- [x] Explosion particle itself is ok, but the extra flare, with additive blending looks off
- [x] Test sound effects (distance volume feature)
- [x] Zooming should not move lists in sidebar (cripples easy scrolling, but it will be replaced by #68)
- [x] Rendering Rally point should work with zooming
- [x] squish particle renders not properly (wrong coordinates?)
- [x] some explosions seem to be wrong (tank big explosion)

**Comment by stefanhendriks** [comment]
A lot has been done, but these things (at the very least) should be addressed to complete this:


- [ ] Windtraps drawing are broken for now:

![image](https://user-images.githubusercontent.com/1332066/90985267-256f2300-e57b-11ea-8433-2fdf9f312fed.png)

- [ ] Game crashes quite often (not sure why).
- [ ] Drawing of placing structure is off. 
- [ ] Tooltip/selecting does not work flawlessly

**Comment by stefanhendriks** [comment]
- [ ] When zoomed out, the repair icons on structures are still 100% which looks weird (icons are bigger than structure):
![image](https://user-images.githubusercontent.com/1332066/90985523-ca3e3000-e57c-11ea-81db-ba98a9509f11.png)

**Comment by stefanhendriks** [comment]
- [ ] When zoomed (in or out), ordering units to attack makes units freeze. (ie, they stop moving, even when half-way cell, and they don't do anything else. They won't attack, nor move). When resetting zoom (with `z`), then clicking on structure to attack works as expected.

**Comment by stefanhendriks** [comment]
- [ ] Prebuild animation is still not zoomed
![image](https://user-images.githubusercontent.com/1332066/90985954-90225d80-e57f-11ea-9495-402f8e3a1809.png)

Expected to be the same 'size' as other structures (taking zooming factor into account)

**Comment by stefanhendriks** [comment]
- [ ] Windtrap shadow offset is wrong when zooming. 

When zoomed in, the shadow is gone:
![image](https://user-images.githubusercontent.com/1332066/90985975-c19b2900-e57f-11ea-8a06-33ed14136ddb.png)

When zoomed out, the shadow is rendered too much to the right/down:
![image](https://user-images.githubusercontent.com/1332066/90985983-d1b30880-e57f-11ea-8e0c-64ee2ce65d98.png)

**Comment by stefanhendriks** [comment]
- [ ] Particles (smoke, explosions, etc) that have been placed are not rendered at the correct place when zooming
![image](https://user-images.githubusercontent.com/1332066/90986012-1b035800-e580-11ea-9e5a-5ebf3ce954bc.png)

It looks like as if, upon creation they are placed on the correct spot, but when zooming, they are moving away from their destination. Rendering of particles bugged?

**Comment by stefanhendriks** [comment]
There is a suspicion that the tile renderer is at fault. All units, bullets, structures and particles now render at the same way and all have the same behavior. It looks off:
![image](https://user-images.githubusercontent.com/1332066/91097043-4e68e400-e65f-11ea-91fb-194d9a83b58f.png)

But, it seems to be correct (as in, @arjenvanderende and I can determine it is correctly using the absolute coordinates and drawing x/y seem to be ok). So it looks like other things are broken.

**Comment by stefanhendriks** [comment]
The reason the map rendering looks off is because:

1. The rendering of tiles should not be using absolute coordinates
2. The position of the camera should change when zooming, ie, when zooming in (less visible) the camera should (assuming focus point is center) move to the down/right. When zooming out it should be up/left.

**Comment by stefanhendriks** [comment]
Got some progress:
![image](https://user-images.githubusercontent.com/1332066/91355633-b994f080-e7ee-11ea-9777-b7d72cafa60d.png)

looks a lot better already. But a lot of things still need to be done.
