### ISSUE TITLE
Redesign sidebar

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#68]
The sidebar is based on the old C&C days. The sidebar in C&C Remastered is better, it removes the need for scrolling through lists (and using the scroll buttons). It is a bit wider, but it is not so high which makes up for it.

## Todo
- [x] upgrades into separate list (as C&C3)
   - [x] configure all upgrades in code
- [x] Do not render build count for upgrades
- [x] When structure is placed evaluate upgrades.
- [x] When structure is destroyed evaluate upgrades.
- [x] When upgrade is done, re-evaluate upgrades.
  - [x] test & make sure it wont delete previous upgrade
- [x] move minimap up
   - [x] when no minimap available, show house emblem
- [x] minimap: Without an outpost and/or sufficient power, the radar screen will only show friendly buildings.
- [x] move Order button to the sidebar
- [x] credit-bar (centered) should be 8 bit
- [x] sidebar should show power usage
- [x] spice usage
- [x] minimap: when clicking on it, you should jump properly to the place you where clicking... (regression)
- [x] topbar, show information? (selected structure? power/spice usage?)
- [x] Upgrading should limit build options (ie CONSTYARD upgrading should limit CONSTYARD items to being built) - and show it on icon
- [x] When a unit/structure is built, the related UPGRADE cannot be executed (and should show it)
- [x] bug: Cancel placement does not work
- [x] bug: when building house of IX, it adds Deviator/Devastator etc even when no heavy factory is present.
- [x] mouse selecting/rectangle draws over sidebar

Example of C&C (Red alert) Remastered sidebar:

![image](https://user-images.githubusercontent.com/1332066/92304673-59394800-ef80-11ea-9453-d58efbefd8c4.png)

**Comment by stefanhendriks** [comment]
All upgrades that where in the 'old' code , are now in the new code. Not sure if all upgrades are there, but for now it is ok.
